services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    environment:
      - ENV_PATH=.env
    ports:
      - "85:85"
      - "50052:50052"
    depends_on:
      - db
    restart: on-failure
    networks:
      - app_network
    profiles:
      - frontend
      - full

  generate:
    build:
      context: ./generate-service
      dockerfile: Dockerfile
    ports:
      - "90:90"
    depends_on:
      - api
      - textgen
    networks:
      - app_network
    profiles:
      - full

  textgen:
    build:
      context: ./textgen-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    restart: on-failure
    networks:
      - app_network
    profiles:
      - full

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
      - db
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    networks:
      - app_network
    profiles:
      - frontend
      - full

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gpt_network
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql_data:/var/lib/postgresql/data
      - ./data/migrations:/docker-entrypoint-initdb.d
    networks:
      - app_network
    profiles:
      - frontend
      - full

networks:
  app_network:
    driver: bridge