services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV_PATH=.env
    ports:
      - "85:85"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gpt_network
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/migrations:/docker-entrypoint-initdb.d/migrations

volumes:
  db_data: