services:
  api:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    environment:
      - ENV_PATH=.env
    ports:
      - "85:85"
    depends_on:
      - db
      - textgen
    restart: on-failure
    networks:
      - app_network

  textgen:
    build:
      context: ./textgen-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    restart: on-failure
    networks:
      - app_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
      - textgen
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gpt_network
    ports:
      - "5432:5432"
    volumes:
      - ./api-service/internal/db/postgresql_data:/var/lib/postgresql/data
      - ./api-service/internal/db/migrations:/docker-entrypoint-initdb.d
    networks:
      - app_network

networks:
  app_network:
    driver: bridge