// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package factory

import (
	"github.com/Crabocod/gpt_network/api-service/internal/app/apiserver"
	"github.com/Crabocod/gpt_network/api-service/internal/app/grpcserver"
	"github.com/Crabocod/gpt_network/api-service/internal/config"
	"github.com/Crabocod/gpt_network/api-service/internal/db"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	sqlxDB, err := db.Connect(configConfig)
	if err != nil {
		return nil, err
	}
	apiServer := apiserver.New(sqlxDB, configConfig)
	grpcServer := grpcserver.New(sqlxDB, configConfig)
	appApp := New(apiServer, grpcServer)
	return appApp, nil
}
