[database]
db_host="db"
db_port="5432"
db_user="root"
db_password="root"
db_name="gpt_network"
db_sslmode="disable"

[jwt]
jwt_access_secret="71wdyirsaywkwznuzo75b055wyddnu"
jwt_refresh_secret="71wdyirsaywkwznuzo75b055wyddnu"

[logger]
log_level="debug"

[api_server]
bind_addr=":85"

[grpc_server]
bind_addr=":50052"