[database]
host="db"
port="5432"
user="root"
password="root"
name="gpt_network"
sslmode="disable"

[jwt]
accessSecret="71wdyirsaywkwznuzo75b055wyddnu"
refreshSecret="71wdyirsaywkwznuzo75b055wyddnu"

[logger]
logLevel="debug"

[apiServer]
bindAddr=":85"

[grpcServer]
bindAddr=":50052"