# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proto\"7\n\x0fGenerateRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\"\"\n\x10GenerateResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"4\n\x0fSavePostRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\"#\n\x10SavePostResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"%\n\x0eGetPostRequest\x12\x13\n\x0b\x61uthor_name\x18\x01 \x01(\t\"5\n\x0fGetPostResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\t\x12\x11\n\tpost_text\x18\x02 \x01(\t\"[\n\x12SaveCommentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0b\x61uthor_name\x18\x02 \x01(\t\x12\x0f\n\x07post_id\x18\x03 \x01(\t\x12\x11\n\tparent_id\x18\x04 \x01(\t\"&\n\x13SaveCommentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32Q\n\x0eTextGenService\x12?\n\x0cGenerateText\x12\x16.proto.GenerateRequest\x1a\x17.proto.GenerateResponse2\xc9\x01\n\nApiService\x12;\n\x08SavePost\x12\x16.proto.SavePostRequest\x1a\x17.proto.SavePostResponse\x12\x44\n\x0bSaveComment\x12\x19.proto.SaveCommentRequest\x1a\x1a.proto.SaveCommentResponse\x12\x38\n\x07GetPost\x12\x15.proto.GetPostRequest\x1a\x16.proto.GetPostResponseB\x0cZ\n./go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n./go/proto'
  _globals['_GENERATEREQUEST']._serialized_start=24
  _globals['_GENERATEREQUEST']._serialized_end=79
  _globals['_GENERATERESPONSE']._serialized_start=81
  _globals['_GENERATERESPONSE']._serialized_end=115
  _globals['_SAVEPOSTREQUEST']._serialized_start=117
  _globals['_SAVEPOSTREQUEST']._serialized_end=169
  _globals['_SAVEPOSTRESPONSE']._serialized_start=171
  _globals['_SAVEPOSTRESPONSE']._serialized_end=206
  _globals['_GETPOSTREQUEST']._serialized_start=208
  _globals['_GETPOSTREQUEST']._serialized_end=245
  _globals['_GETPOSTRESPONSE']._serialized_start=247
  _globals['_GETPOSTRESPONSE']._serialized_end=300
  _globals['_SAVECOMMENTREQUEST']._serialized_start=302
  _globals['_SAVECOMMENTREQUEST']._serialized_end=393
  _globals['_SAVECOMMENTRESPONSE']._serialized_start=395
  _globals['_SAVECOMMENTRESPONSE']._serialized_end=433
  _globals['_TEXTGENSERVICE']._serialized_start=435
  _globals['_TEXTGENSERVICE']._serialized_end=516
  _globals['_APISERVICE']._serialized_start=519
  _globals['_APISERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
