# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextGenServiceStub(object):
    """Сервис для генерации текста
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/proto.TextGenService/GenerateText',
                request_serializer=service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=service__pb2.GenerateResponse.FromString,
                _registered_method=True)


class TextGenServiceServicer(object):
    """Сервис для генерации текста
    """

    def GenerateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=service__pb2.GenerateRequest.FromString,
                    response_serializer=service__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TextGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.TextGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextGenService(object):
    """Сервис для генерации текста
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TextGenService/GenerateText',
            service__pb2.GenerateRequest.SerializeToString,
            service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ApiServiceStub(object):
    """Сервис для общения с API
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SavePost = channel.unary_unary(
                '/proto.ApiService/SavePost',
                request_serializer=service__pb2.SavePostRequest.SerializeToString,
                response_deserializer=service__pb2.SavePostResponse.FromString,
                _registered_method=True)
        self.SaveComment = channel.unary_unary(
                '/proto.ApiService/SaveComment',
                request_serializer=service__pb2.SaveCommentRequest.SerializeToString,
                response_deserializer=service__pb2.SaveCommentResponse.FromString,
                _registered_method=True)
        self.GetPost = channel.unary_unary(
                '/proto.ApiService/GetPost',
                request_serializer=service__pb2.GetPostRequest.SerializeToString,
                response_deserializer=service__pb2.GetPostResponse.FromString,
                _registered_method=True)


class ApiServiceServicer(object):
    """Сервис для общения с API
    """

    def SavePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveComment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SavePost': grpc.unary_unary_rpc_method_handler(
                    servicer.SavePost,
                    request_deserializer=service__pb2.SavePostRequest.FromString,
                    response_serializer=service__pb2.SavePostResponse.SerializeToString,
            ),
            'SaveComment': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveComment,
                    request_deserializer=service__pb2.SaveCommentRequest.FromString,
                    response_serializer=service__pb2.SaveCommentResponse.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=service__pb2.GetPostRequest.FromString,
                    response_serializer=service__pb2.GetPostResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.ApiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.ApiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApiService(object):
    """Сервис для общения с API
    """

    @staticmethod
    def SavePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ApiService/SavePost',
            service__pb2.SavePostRequest.SerializeToString,
            service__pb2.SavePostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveComment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ApiService/SaveComment',
            service__pb2.SaveCommentRequest.SerializeToString,
            service__pb2.SaveCommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.ApiService/GetPost',
            service__pb2.GetPostRequest.SerializeToString,
            service__pb2.GetPostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
