# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TextGenServiceStub(object):
    """Сервис для генерации текста
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/proto.TextGenService/GenerateText',
                request_serializer=service__pb2.GenerateRequest.SerializeToString,
                response_deserializer=service__pb2.GenerateResponse.FromString,
                _registered_method=True)


class TextGenServiceServicer(object):
    """Сервис для генерации текста
    """

    def GenerateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextGenServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=service__pb2.GenerateRequest.FromString,
                    response_serializer=service__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.TextGenService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.TextGenService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TextGenService(object):
    """Сервис для генерации текста
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.TextGenService/GenerateText',
            service__pb2.GenerateRequest.SerializeToString,
            service__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SaveTextServiceStub(object):
    """Сервис для сохранения сгенерированного текста в БД
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveGeneratedText = channel.unary_unary(
                '/proto.SaveTextService/SaveGeneratedText',
                request_serializer=service__pb2.SaveRequest.SerializeToString,
                response_deserializer=service__pb2.SaveResponse.FromString,
                _registered_method=True)


class SaveTextServiceServicer(object):
    """Сервис для сохранения сгенерированного текста в БД
    """

    def SaveGeneratedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SaveTextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveGeneratedText': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveGeneratedText,
                    request_deserializer=service__pb2.SaveRequest.FromString,
                    response_serializer=service__pb2.SaveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.SaveTextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.SaveTextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SaveTextService(object):
    """Сервис для сохранения сгенерированного текста в БД
    """

    @staticmethod
    def SaveGeneratedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.SaveTextService/SaveGeneratedText',
            service__pb2.SaveRequest.SerializeToString,
            service__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
